create table CARONA (
	ID INTEGER,
	MOTORISTA_ID INTEGER,
	CARRO_ID INTEGER,
	ORIGEM INTEGER,
	DESTINO INTEGER,
	VAGAS INTEGER,
	DIA DATE,
	HORARIO TIME,
	NOTA INTEGER,

	CONSTRAINT CARONA_PK PRIMARY KEY (ID)
);
