create table CARONA (
	ID INTEGER,
	MOTORISTA_ID INTEGER,
	CARRO_ID INTEGER,
	ORIGEM INTEGER,
	DESTINO INTEGER,
	VAGAS INTEGER,
	DIA VARCHAR(20),
	HORARIO VARCHAR(20),
	NOTA VARCHAR(20),

	CONSTRAINT CARONA_PK PRIMARY KEY (ID)
);
