create table MODELO_CARRO (
	ID INTEGER NOT NULL,
	NOME VARCHAR(50),
	MONTADORA VARCHAR(50),
	
	CONSTRAINT MODELO_CARRO_PK PRIMARY KEY (ID)
);
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (1, 'Ram 2500 Club', 'Dodge');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (2, 'Sedona', 'Kia');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (3, 'Breeze', 'Plymouth');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (4, 'TT', 'Audi');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (5, 'Ram 2500', 'Dodge');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (6, 'CR-V', 'Honda');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (7, 'Mazda5', 'Mazda');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (8, 'Cayenne', 'Porsche');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (9, 'Ram 1500', 'Dodge');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (10, 'Escort', 'Ford');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (11, 'LS', 'Lexus');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (12, 'Odyssey', 'Honda');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (13, 'S-Series', 'Saturn');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (14, '90', 'Audi');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (15, 'Econoline E150', 'Ford');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (16, 'Astro', 'Chevrolet');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (17, 'Grand Prix', 'Pontiac');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (18, 'Taurus X', 'Ford');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (19, 'Tempo', 'Ford');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (20, 'Sidekick', 'Suzuki');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (21, 'SL-Class', 'Mercedes-Benz');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (22, 'Catera', 'Cadillac');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (23, 'Villager', 'Mercury');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (24, 'Somerset', 'Buick');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (25, 'Tempo', 'Ford');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (26, 'Savana 2500', 'GMC');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (27, 'GL-Class', 'Mercedes-Benz');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (28, '745', 'BMW');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (29, 'Lancer', 'Mitsubishi');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (30, 'TL', 'Acura');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (31, 'Silhouette', 'Oldsmobile');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (32, 'Enclave', 'Buick');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (33, 'Ram 2500', 'Dodge');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (34, 'Ram 3500', 'Dodge');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (35, 'Legacy', 'Subaru');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (36, 'Vantage', 'Aston Martin');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (37, 'Roadster', 'Tesla');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (38, 'Terrain', 'GMC');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (39, 'M', 'Infiniti');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (40, '90', 'Audi');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (41, 'F250', 'Ford');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (42, 'Trooper', 'Isuzu');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (43, 'Millenia', 'Mazda');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (44, 'Safari', 'GMC');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (45, 'Tribute', 'Mazda');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (46, 'Routan', 'Volkswagen');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (47, '500SL', 'Mercedes-Benz');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (48, 'C-Class', 'Mercedes-Benz');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (49, 'Riviera', 'Buick');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (50, '5 Series', 'BMW');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (51, 'Integra', 'Acura');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (52, 'DTS', 'Cadillac');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (53, 'Probe', 'Ford');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (54, 'Thunderbird', 'Ford');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (55, 'Escort', 'Ford');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (56, 'Park Avenue', 'Buick');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (57, 'Tracker', 'Geo');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (58, 'Grand Cherokee', 'Jeep');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (59, 'Legacy', 'Subaru');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (60, 'S80', 'Volvo');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (61, 'Maxima', 'Nissan');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (62, 'Town Car', 'Lincoln');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (63, 'Topaz', 'Mercury');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (64, 'B-Series', 'Mazda');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (65, 'Rondo', 'Kia');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (66, 'Type 2', 'Volkswagen');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (67, 'Element', 'Honda');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (68, '530', 'BMW');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (69, 'Mazda3', 'Mazda');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (70, '2500', 'Chevrolet');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (71, 'MKX', 'Lincoln');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (72, 'Thunderbird', 'Ford');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (73, 'E-Class', 'Mercedes-Benz');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (74, 'LS', 'Lexus');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (75, 'W201', 'Mercedes-Benz');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (76, 'Pajero', 'Mitsubishi');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (77, 'SC', 'Lexus');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (78, 'Camaro', 'Chevrolet');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (79, '1500', 'Chevrolet');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (80, 'XF', 'Jaguar');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (81, 'Bonneville', 'Pontiac');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (82, 'Sonata', 'Hyundai');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (83, 'Tracker', 'Chevrolet');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (84, 'Escalade EXT', 'Cadillac');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (85, 'A8', 'Audi');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (86, 'Boxster', 'Porsche');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (87, 'Corvette', 'Chevrolet');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (88, 'Quest', 'Nissan');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (89, 'M-Class', 'Mercedes-Benz');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (90, '323', 'Mazda');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (91, 'RX', 'Lexus');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (92, 'Traverse', 'Chevrolet');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (93, 'CC', 'Volkswagen');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (94, 'Enclave', 'Buick');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (95, 'Mirage', 'Mitsubishi');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (96, '300', 'Chrysler');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (97, 'Alcyone SVX', 'Subaru');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (98, 'GTI', 'Volkswagen');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (99, 'Town & Country', 'Chrysler');
insert into MODELO_CARRO (ID, NOME, MONTADORA) values (100, 'Econoline E350', 'Ford');
