create table CAMPUS (
	ID INTEGER,
	NOME VARCHAR(14),

	CONSTRAINT CAMPUS_PK PRIMARY KEY (ID)
);

create table CARONA (
	ID INTEGER,
	MOTORISTA_ID INTEGER,
	CARRO_ID INTEGER,
	ORIGEM INTEGER,
	DESTINO INTEGER,
	VAGAS INTEGER,
	DIA DATE,
	HORARIO TIME,
	NOTA INTEGER,

	CONSTRAINT CARONA_PK PRIMARY KEY (ID)
);

create table CARRO (
	ID INTEGER NOT NULL,
	PLACA VARCHAR(50),
	USUARIO_ID INTEGER NOT NULL,
	MODELO_ID INTEGER NOT NULL,

	CONSTRAINT CARRO_PK PRIMARY KEY (ID)
);

create table LUGAR (
	ID INTEGER NOT NULL,
	NOME VARCHAR(20) NOT NULL,
	
	CONSTRAINT LUGAR_PK PRIMARY KEY (ID)
);

create table MODELO_CARRO (
	ID INTEGER NOT NULL,
	NOME VARCHAR(50),
	MONTADORA VARCHAR(50),
	
	CONSTRAINT MODELO_CARRO_PK PRIMARY KEY (ID)
);

CREATE TABLE MOTORISTA (
    USUARIO_ID INTEGER,
    CARRO_ID INTEGER,

    CONSTRAINT MOTORISTA_PK PRIMARY KEY (USUARIO_ID)
);

create table PASSAGEIRO (
	ID INTEGER,
	CARONA_ID INTEGER,
	USUARIO_ID INTEGER,

	CONSTRAINT PASSAGEIRO_PK PRIMARY KEY (ID)
);


create table RESERVA (
	ID INTEGER,
	USUARIO_ID INTEGER,
	CARONA_ID INTEGER,

	CONSTRAINT RESERVA_PK PRIMARY KEY (ID)
);
create table USUARIO (
	ID INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(50),
	MATRICULA VARCHAR(50),
	BAIRRO_ID INTEGER,
	EMAIL VARCHAR(50),

	CONSTRAINT USUARIO_PK PRIMARY KEY (ID)
);


ALTER TABLE CARRO ADD
    CONSTRAINT FK_MODELO FOREIGN KEY(MODELO_ID) REFERENCES MODELO_CARRO(ID);

ALTER TABLE CARRO ADD
    CONSTRAINT FK_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID);

ALTER TABLE USUARIO ADD
    CONSTRAINT FK_BAIRRO FOREIGN KEY (BAIRRO_ID) REFERENCES LUGAR(ID);

ALTER TABLE PASSAGEIRO ADD
    CONSTRAINT FK_CARONA_ID FOREIGN KEY (CARONA_ID) REFERENCES CARONA(ID);

ALTER TABLE PASSAGEIRO ADD
    CONSTRAINT FK_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID);

ALTER TABLE RESERVA ADD
    CONSTRAINT FK_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID);

ALTER TABLE RESERVA ADD
    CONSTRAINT FK_CARONA_ID FOREIGN KEY (CARONA_ID) REFERENCES CARONA(ID);

ALTER TABLE CARONA ADD
    CONSTRAINT FK_MOTORISTA_ID FOREIGN KEY (MOTORISTA_ID) REFERENCES MOTORISTA(USUARIO_ID);

ALTER TABLE CARONA ADD
    CONSTRAINT FK_ORIGEM_ID FOREIGN KEY (ORIGEM) REFERENCES LUGAR(ID);

ALTER TABLE CARONA ADD
    CONSTRAINT FK_DESTINO_ID FOREIGN KEY (DESTINO) REFERENCES LUGAR(ID);

ALTER TABLE CAMPUS ADD
    CONSTRAINT FK_LUGAR_ID FOREIGN KEY (ID) REFERENCES LUGAR(ID);
