ALTER TABLE CARRO ADD
    CONSTRAINT FK_MODELO FOREIGN KEY(MODELO_ID) REFERENCES MODELO_CARRO(ID);

ALTER TABLE CARRO ADD
    CONSTRAINT FK_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID);

ALTER TABLE USUARIO ADD
    CONSTRAINT FK_BAIRRO FOREIGN KEY (BAIRRO_ID) REFERENCES LUGAR(ID);

ALTER TABLE PASSAGEIRO ADD
    CONSTRAINT FK_CARONA_ID FOREIGN KEY (CARONA_ID) REFERENCES CARONA(ID);

ALTER TABLE PASSAGEIRO ADD
    CONSTRAINT FK_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID);

ALTER TABLE RESERVA ADD
    CONSTRAINT FK_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID);

ALTER TABLE RESERVA ADD
    CONSTRAINT FK_CARONA_ID FOREIGN KEY (CARONA_ID) REFERENCES CARONA(ID);

ALTER TABLE CARONA ADD
    CONSTRAINT FK_MOTORISTA_ID FOREIGN KEY (MOTORISTA_ID) REFERENCES MOTORISTA(ID);

ALTER TABLE CARONA ADD
    CONSTRAINT FK_ORIGEM_ID FOREIGN KEY (ORIGEM_ID) REFERENCES LUGAR(ID);

ALTER TABLE CARONA ADD
    CONSTRAINT FK_DESTINO_ID FOREIGN KEY (DESTINO_ID) REFERENCES LUGAR(ID);

ALTER TABLE CAMPUS ADD
    CONSTRAINT FK_LUGAR_ID FOREIGN KEY (ID) REFERENCES LUGAR(ID);