ALTER TABLE CARRO ADD
    CONSTRAINT FK_MODELO FOREIGN KEY(MODELO_ID) REFERENCES MODELO_CARRO(ID));

ALTER TABLE CARRO ADD
    CONSTRAINT FK_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID);

ALTER TABLE USUARIO ADD
    CONSTRAINT FK_BAIRRO FOREIGN KEY (BAIRRO_ID) REFERENCES LUGAR(ID));